### ISSUE TITLE
Errors on mac os x.

### ISSUE THREAD

**Issue by lndbrg** [jkramer/shell-fm#1]
Hi,

There are a few tiny problems regarding running shell-fm on mac os x. Since I am not a c programmer i can not fix them myself, but i am willing to contribute in anyway possible.

I installed libao and libmad through macports, then i compiled shell-fm and it plays fine but it keeps spewing this error message on stderr:

> The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
> Break on **THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC**() to debug.

The problem is with Mac OS X CoreFoundation and processes that uses fork, without exec*()-ing afterwards.
A bit more information can be found here: http://developer.apple.com/releasenotes/CoreFoundation/CoreFoundation.html
Search for: CoreFoundation and fork()

Best Regards
Olle

**Comment by jkramer** [comment]
I've never heard of CoreFoundation and I have no idea what it has to do with shell-fm, but complaining about forks without execs in random apps is just stupid. Try to get rid of it if you can or you'll have to live with the error messages, because forking without execing is just the way shell-fm works and there's no way around it. There's an old experimental branch using threads instead of forks which you might want to try, but it's not tested very well and it's missing some newer features. Sorry.

**Comment by mdonoughe** [comment]
I run shell-fm on Mac OS X 10.5.7 and I do not see this problem. What version of Mac OS are you running?

**Comment by lndbrg** [comment]
Mac OS X 10.5.7. shell-fm 0.6

mdonoughe, how did you install it? How do you run it (parameters/rc-file)?

**Comment by lndbrg** [comment]
jkramer. Just a clarification about CF, it is Apples C API for Mac OS X so it is impossible to get rid off. But since i run zsh i was planning on using the key bindings anyway, just wanted to let you know of the issue.

**Comment by mdonoughe** [comment]
I just run make in the shell-fm folder.

Have you tried a shell-fm.rc as simple as
    username=mdonoughe
    password=secret
    default-radio=lastfm://user/mdonoughe/personal

and running shell-fm with no parameters? You haven't edited the Makefile or anything?

**Comment by lndbrg** [comment]
i was runnin shell-fm without an rc at all. No edits to the make file. Where did you install libmad/libao from?

**Comment by mdonoughe** [comment]
Ah. I was using libao 0.8.8_1 from MacPorts. libao 0.8.8_2(which I for some reason had compiled but never activated) produces the errors you are seeing. The easy solution I guess would be to downgrade libao to 0.8.8_1.

**Comment by lndbrg** [comment]
Thank you. I will downgrade the lib then. jkramer, sorry for bothering you.

**Comment by mdonoughe** [comment]
The issue is that the newer libao from MacPorts uses AudioUnits rather than CoreAudio, and apparently AudioUnits should not be used in a background process this way.

**Comment by lndbrg** [comment]
Yes, i have checked out an odler version of it now, Latest 0.8.8_1 without AudioUnit is revision 31766

**Comment by dcherryholmes** [comment]
I downgraded to rev 31766 via svn, compiled successfully, ensured the later version was removed, and successfully compiled shell-fm.  It plays, but I still get the same error.  Any thoughts?
