### ISSUE TITLE
doesn't build on xubuntu 64bit

### ISSUE THREAD

**Issue by maritz** [jkramer/shell-fm#10]
Last few lines of make:

libshellfm.a(play.o): In function `playback':
play.c:(.text+0x585): undefined reference to`ao_initialize'
play.c:(.text+0x635): undefined reference to `ao_default_driver_id'
play.c:(.text+0x694): undefined reference to`ao_open_live'
play.c:(.text+0x857): undefined reference to `mad_decoder_init'
play.c:(.text+0x861): undefined reference to`mad_decoder_run'
play.c:(.text+0x869): undefined reference to `mad_decoder_finish'
collect2: ld returned 1 exit status
make[1]: *** [shell-fm] Error 1
make[1]: Leaving directory`/home/moritz/repos/shell-fm/source'
make: **\* [shell-fm] Error 2

Same for master, v0.7 and v0.6. (haven't tried any other tags/branches)
libmad0-dev and libao-dev are installed.

**Comment by bartman** [comment]
maritz, can you run this command on your system:

(1) pkg-config --list-all | grep -e mad -e ao

Maybe you're missing pkg-config ?

If the above works, do you get any output for this:

(2) pkg-config --cflags mad
(3) pkg-config --cflags ao

I am missing some info in the above output, to figure out what's going on.  Of particular interest are the parameters passed to gcc and ld.  Can you paste the entire output of make into a gist page?

Cheers,
-Bart

**Comment by maritz** [comment]
I don't have pgk-config. Installing now, 1 mom :)

edit: Okay, compiled and installed.

Next problem: After entering username+pwd I get: 
Invalid HTTP: HTTP/1.1 503 Service Unavailable
  from: http://ws.audioscrobbler.com/radio/handshake.php?version=0.1&platform=linux&username=myusername&passwordmd5=mymd5password&debug=0&language=en

Calling the url manually in my browser seems to work fine though.

**Comment by jkramer** [comment]
Does the problem still occur? It was probably just a temporary server problem at last.fm.

**Comment by maritz** [comment]
Still happening. 

The Last.fm linux app works but gives this upon start: 

```
Last.fm was unable to start accepting tracks from the plugin for your media player.

Details: Accept socket connection failed. Socket error: 4
```

After clicking OK everything is fine there though.

Maybe this is connected?

**Comment by jkramer** [comment]
Weird, I don't see a reason why this shouldn't work. Are you using a proxy?

**Comment by maritz** [comment]
Nope, no proxy.

**Comment by jkramer** [comment]
I'm getting the same error since a few minutes, looks like last.fms database is down (http://status.last.fm/).

**Comment by maritz** [comment]
Yep, it was. But this time neither the website nor the last.fm linux app worked.
