### ISSUE TITLE
Setting specific volume via network interface is inaccurate

### ISSUE THREAD

**Issue by evilgnome** [jkramer/shell-fm#14]
Examples:
echo "volume 50" | nc.openbsd 127.0.0.1 54311
echo "info %v" | nc.openbsd 127.0.0.1 54311

> > 78%

Trying to set any value >= 64 results in a set volume of 100.

Results seem to be roughly 1.5 times the target value, capped at 100.

**Comment by jkramer** [comment]
The command uses the internal volume representation (int between 0-64).

**Comment by evilgnome** [comment]
Oh, I see. Sorry. It is quite confusing that setting and getting the volume uses two different scales.

**Comment by jkramer** [comment]
I know, it was a rather quick hack. If you can provide a patch, I'll happily apply it. Not sure when I'll have the time to change it.

**Comment by evilgnome** [comment]
Well for my personal needs, it's all good. I'm just making the calls in my front end, not manually, and I've already updated my program to map the volume slider correctly. So it's actually in my interest to just keep it the same (stable).

If you do end up changing it down the line, maybe you'd post a comment here so I get alerted?

Anyway thanks for clearing it up, and again for such an incredible program!

**Comment by jkramer** [comment]
I added support for setting percentual volume. The command syntax is "volume %50" (note the % sign), although "volume 32" still works too, so you don't need to update your program.
