### ISSUE TITLE
NCURSES interface for shell-fm

### ISSUE THREAD

**Issue by anupcshan** [jkramer/shell-fm#28]
It would be good to have an NCURSES interface for shell-fm. It could communicate to the shell-fm daemon over the network.
In case there is no such interface (none shown in the wiki), I would be interested in developing this.

**Comment by jkramer** [comment]
There's no curses client for shell-fm that I know of, so feel free to build one. :)
------Original Message------
From: anupcshan
To: Jonas Kramer
Subject: [GitHub] NCURSES interface for shell-fm [jkramer/shell-fm GH-28]
Sent: Apr 15, 2011 15:47

It would be good to have an NCURSES interface for shell-fm. It could communicate to the shell-fm daemon over the network.
In case there is no such interface (none shown in the wiki), I would be interested in developing this.

## 

Reply to this email directly or view it on GitHub:
https://github.com/jkramer/shell-fm/issues/28
