### ISSUE TITLE
feature request and small man page typo

### ISSUE THREAD

**Issue by fawaf** [jkramer/shell-fm#33]
could you make it so we can rebind the keys for each of the commands in shell-fm like you can in pianobar?

also, in the man page, there are a couple places where you did not finish you sentence:

```
   np-file-format = format-string
          This defines how the information written to your now-playing file will look like. There are several format flags available. Have a look at the
```

and

  ?-color = color
              This allows you to color format elements. The ?  may be the letter of any format flag (without percent). The color is just a normal shell color code match-
              ing "[01];3[0-7]". Whenever the format element is printed to the console, it will have the given color. Have a look at the

**Comment by dark** [comment]
W.r.t. the man page typos, it seems that two sections are misplaced:

> preview-format = format-string 
> daemon = something

Both of them begin inside the previous section (those reported by fawong), so some trailing text ends up in the wrong section.

**Comment by dark** [comment]
Pull request for the manpage problem filed (see issue #34).
