### ISSUE TITLE
.PHONY should include "install"

### ISSUE THREAD

**Issue by ryandesign** [jkramer/shell-fm#36]
On case-insensitive systems like Mac OS X, "make install" fails with the message "make: `install' is up to date." because there is a file "INSTALL" and "install" is not listed as .PHONY.

**Comment by ryandesign** [comment]
The fix for this is included in the following patch:

https://trac.macports.org/browser/trunk/dports/audio/shell-fm/files/patch-Makefile.diff?rev=82139

**Comment by jkramer** [comment]
Added workaround in 48c9b59. You should also tell Apple about this, they might want to fix this. ;)

**Comment by ryandesign** [comment]
I don't believe there is an Apple issue involved here (nor anything Apple isn't already acutely aware of); it's simply a consequence of dealing with case-insensitive filesystems (on any platform, not just Mac OS X) that developers need to take into account.

Thank you for the quick fix.
