### ISSUE TITLE
pausing shell-fm mutes all system audio

### ISSUE THREAD

**Issue by semanticart** [jkramer/shell-fm#40]
using 0.8 (installed on Snow Leopard via homebrew), pressing P silences all audio.

To repro, start playing something in iTunes or youtube, while listening to shell-fm.  Press P.  Note you can't hear anything from any source.

**Comment by henrik-farre** [comment]
adding the following line to ~/.libao (Linux system) fixes it for me:
dev=default

**Comment by semanticart** [comment]
thanks, but it doesn't seem to work on OS X.
