### ISSUE TITLE
OpenSSL - MD5 error...

### ISSUE THREAD

**Issue by ghost** [jkramer/shell-fm#56]
Jonas & team -

Thanks for the user prompt fix and plain text password BUT md5 passwords are now bombing.
The browser output is from the URL entered into chrome.

See output below - Brad )at( verohomies dotcom

======== OUTPUT =========
root@voyage:~/.shell-fm# shell-fm  
Shell.FM v0.8, (C) 2006-2010 by Jonas Kramer
Published under the terms of the GNU General Public License (GPL).

Press ? for help.

Invalid HTTP:   from: http://ws.audioscrobbler.com/radio/handshake.php?version=0.1&platform=linux&username=xxxx&passwordmd5=xxx357c30cf80c2775a3efbb109a4830 &debug=0&language=en
No response.

======== BROWSER ========
session=FAILED
msg=padd md5 not 32 len

======== .RC File =========
root@voyage:~/.shell-fm# more shell-fm.rc
username = xxxxxxx
password-md5 = xxx357c30cf80c2775a3efbb109a4830 
title-format = Now playing %t by %a from %l
screen-format = Now playing %t by %a from %l
term-format = Now playing %t by %a from %l
default-radio = lastfm://user/xxxxxxxx/recommended

**Comment by jkramer** [comment]
Password authentication is gone for a while now, closing this. :)
