### ISSUE TITLE
DEBUG: Chunked! Couldn't scrobble tracks.

### ISSUE THREAD

**Issue by isomorphisms** [jkramer/shell-fm#57]
I get this error pretty much every time I use `shell-fm`. Otherwise I love the program.

**Comment by nzqr** [comment]
Same problem here.

**Comment by isomorphisms** [comment]
I'd be happy to edit some of the code if I knew which file to look at or where to start debugging.

**Comment by linse** [comment]
I have this problem, too. Sometimes I can even see the track I am listening to on my last.fm page, but after it is finished it disappears from the page.

**Comment by jkramer** [comment]
This shouldn't occur anymore since chunked HTTP responses have implemented for some time now. Let me know if it's still a problem.
