### ISSUE TITLE
Make can't find libmad and neither can I

### ISSUE THREAD

**Issue by isomorphisms** [jkramer/shell-fm#58]
Just installed `libmad`, `libao`, and `libtagc` from `apt-get` in Ubuntu 12.04.

`
make -C source
Package mad was not found in the pkg-config search path.
Perhaps you should add the directory containing`mad.pc'
to the PKG_CONFIG_PATH environment variable
No package 'mad' found
Package ao was not found in the pkg-config search path.
Perhaps you should add the directory containing `ao.pc'
to the PKG_CONFIG_PATH environment variable
No package 'ao' found
make[1]: Entering directory`/home/mars/dev/shell-fm/source'
cc -Os -Wall -MD -W -I./include/ -DLIBAO     -c -o play.o play.c
play.c:26:17: fatal error: mad.h: No such file or directory
compilation terminated.
make[1]: **\* [play.o] Error 1
make[1]: Leaving directory `/home/mars/dev/shell-fm/source'
make: *** [shell-fm] Error 2
`

**Comment by jkramer** [comment]
You'll also need the *-dev packages (libmad-dev etc).
