### ISSUE TITLE
Listening Now

### ISSUE THREAD

**Issue by kazuldur** [jkramer/shell-fm#6]
I would love to have "Listening Now" feature in shell-fm.

**Comment by jkramer** [comment]
Can you explain that?

**Comment by jkramer** [comment]
Closed. Can be done using the np-cmd option.

**Comment by sleeksorrow** [comment]
Can we please reopen this?
When I play with official lastfm player, my friends can see this on their page:
http://twitpic.com/2m2ptr
But when I play with shell-fm, they see this
http://twitpic.com/2m2pvv
So shell-fm does not send the "listening now" info. And I see no way to transfer that via the np-cmd option. If there is one, I'd need some more details (perhaps calling a specific URL with wget or something like that and give track info by URL option?)

**Comment by sleeksorrow** [comment]
To give some more information: I thiink it's the "The Now-Playing Notification" as described in this document: http://www.last.fm/api/submissions#np

**Comment by jkramer** [comment]
Added support for this now-playing-notifications in master.

**Comment by sleeksorrow** [comment]
Wow - 2 days for a minor feature request. I'm impressed! And it works like a charm, thank you!
