### ISSUE TITLE
"Handshake failed." -- scrobbling no longer occurs. Probably outdated API usage.

### ISSUE THREAD

**Issue by AndydeCleyre** [jkramer/shell-fm#64]
As of September 3rd, each time a new song begins, shell-fm prints "Handshake failed." and no tracks are scrobbled to the user's profile. I believe shell-fm is using an outdated Last.fm API protocol.

Requests should be made to _http://ws.audioscrobbler.com/2.0/_ and provide the required parameters listed at _http://www.last.fm/api/show/track.scrobble_, but shell-fm appears to converse with _http://post.audioscrobbler.com/_ instead -- at least in _submit.c_ and _service.c_.

**Comment by AndydeCleyre** [comment]
Today scrobbling works again, even though there has been no shell-fm code change, and even though shell-fm complains
"DEBUG: Chunked!
DEBUG: Chunked!
Couldn't scrobble track(s)."

In shell-fm's wisdom it has also successfully submitted all of yesterday's activities. That's great.

Still, I think the API protocol used in shell-fm should be updated for reliability and future-safety.

**Comment by jkramer** [comment]
Please check out the api-v2 branch for the implementation of the new API.
