### ISSUE TITLE
New streaming protocol notice:

### ISSUE THREAD

**Issue by MrBryan** [jkramer/shell-fm#66]
I'm assuming I got this because of shell-fm:

We're writing you to let you know that there will soon be a change to Last.fm radio that may affect you. Our stats show that you've listened to radio through an application that uses our old streaming protocol. On 1 December we will deprecate this old protocol, so in some applications radio will no longer work.

If you would like to continue enjoying Last.fm Radio, consider upgrading to a new application or using http://www.last.fm/listen

Thanks,
The Last.fm Team

**Comment by professorjamesmoriarty** [comment]
It seems to have gone out to me as well, I only use the website and shell-fm so stands to reason some breakage will be coming.

**Comment by kasbah** [comment]
Admittedly I only spent a little time trying to research it but I would really like to know what exactly is changing. Is there a summary somewhere?

**Comment by MrBryan** [comment]
I dug around a bit, too and couldn't find anything. Wonder if they're
planning to close it off to only their platforms.

**Comment by jkramer** [comment]
The new API is described here: http://www.last.fm/api/
I'm working on the implementation, however this is quite a piece of work as it is rather complex compared to the old simple plain text requests/responses, includes a lot of XML/JSON parsing etc. I hope I can find time to work on it this weekend, but I can't promise that it'll be finished by Dec 1st. Sorry for that.

**Comment by wiwie** [comment]
Anyways nice to hear, that shell-fm is still alive.

**Comment by ghost** [comment]
thanks for working on this.

**Comment by jkramer** [comment]
Here's the branch for testing: https://github.com/jkramer/shell-fm/tree/api-v2

**Comment by jkramer** [comment]
I'm closing this issue now. If you find problems with the new version, please create separate issues for them.
