### ISSUE TITLE
api-v2: no permission to stream

### ISSUE THREAD

**Issue by sleeksorrow** [jkramer/shell-fm#71]
I'm unable to play any stream or station with api-v2. I have authenticated correctly, but when starting a station it tells me:

radio url> users/sleeksorrow/personal
Sorry, couldn't set station to users/sleeksorrow/personal. The Webservices API key supplied does not have permission to stream / create new radio trials.

Thank you for your help!

**Comment by sleeksorrow** [comment]
Is it possible, that if I use any third party app and the new api, that I need to be a subscriber, even when I'm residing in Germany?

**Comment by jkramer** [comment]
Yes that's right, streaming with the new API is only allowed for subscribers. :(
-----Original Message-----

**Comment by arrache-coeur** [comment]
same here...
radio url> artist/ramones
Sorry, couldn't set station to artist/ramones. The Webservices API key supplied does not have permission to stream / create new radio trials.

:-(
