### ISSUE TITLE
can i use new api with api account?

### ISSUE THREAD

**Issue by ohnonot** [jkramer/shell-fm#73]
hello,
firstly, i apologize that the nature of my post doesn't really fit in here but there's no other forum for shell-fm.
it still might be useful for improving shell-fm, which i've been using happily for over a year.
but recently, i cannot use it anymore though last.fm works normally from the web browser.

after reading https://github.com/jkramer/shell-fm/issues/71, which is very much like my own problem, i thought all hope is lost - but then i found www.last.fm/group/Last.fm+Web+Services/forum/21604/_/2188288 and managed to get myself an api account.

is it possible to use shell-fm with the api key i get?
i tried to manually replace the api key in this:

> Please open http://www.last.fm/api/auth/?token=xxxxxxxxxxxxxxx&api_key=xxxxxxxxxxxxxxxx in your browser to authorize shell-fm.

(it's the message the newest shell-fm gives after first start)

and after that requested a token from www.last.fm/api/show/auth.getToken and replaced it in the token file in the .shell-fm folder, but then i get this:

> Invalid authentication token supplied.
> Failed to create session. Please refresh authorization.
> Please open http://www.last.fm/api/auth/?token=xxxxxxxxxxxxxxxxx&api_key=xxxxxxxxxxxxx in your browser to authorize shell-fm.

---so, how can i use those api keys? there's 2, the api key and a "Secret".

i've made cosmetic modifications to sthe shell-fm source code before,so if it's just a question of replacing one code with another, i might do it. and share my results.

thanks in advance.

**Comment by ohnonot** [comment]
i tried to replace the 2 keys i found in shell-fm/source/include/rest.h with those i got from creating the api account. i still get the same error message:

> Sorry, couldn't set station to users/xxxxx/personal. The Webservices API key supplied does not have permission to stream / create new radio trials.
- i really don't know if this is last.fm policy or if it is sth that can be repaired in shell-fm.

explain:
i never paid for my account but have been using it for 5 years or so, always able to access these features: change radio stations, download free tracks, unlimited listening - afaik that's as good as it gets.
also with shell-fm during the last year i never felt any limitation.

now #71 mentioned in my first post suggests that without a subscription i can't use 3rd party apps anymore.
however the last.fm forum link suggests that it is still possible to use last.fm apps with a "test api key" if i get an api account, free.
which i did.

so here i am wondering.
i'm not much of a coder (yet), sorry to say.

btw, i can still listen to last.fm with vagalume, without any modifications - but i can't change stations, it always plays my "recommended".
vagalume has been last updated over a year ago (it's in debian and ubuntu repos).

**Comment by Mischi** [comment]
have you solved this problem?

**Comment by jkramer** [comment]
This is nothing you can "fix" in shell-fm. last.fm decided that you have to pay for a subscription to be able to use 3rd party clients, nothing we can do about it. These limitation do not depend on the API key. So if you're using a test API key, you'll still need a valid account that's allowed to stream.

**Comment by Mischi** [comment]
ah ok, thanks!
