### ISSUE TITLE
Feature Request: CLI flag to supply custom shell-fm.rc path at runtime

### ISSUE THREAD

**Issue by evilgnome** [jkramer/shell-fm#8]
There's probably not much demand for this feature, but it would help me. I'm writing a gui frontend to shell-fm, and I'd like to use a custom configuration file without affecting the original file.

**Comment by jkramer** [comment]
You can set the environment variable $SHELL_FM_HOME to an alternative directory (default is ~/.shell-fm/). Does this help?

**Comment by evilgnome** [comment]
Yes, this is perfect. Thanks! I hereby withdraw my request.
