### ISSUE TITLE
No longer scrobbles tracks.

### ISSUE THREAD

**Issue by its-danny** [jkramer/shell-fm#9]
For the last few months, shell-fm hasn't been scrobbeling (everything else seems to work fine, though). Last time I was in IRC a few other people were having the same problem, figured I'd leave this here as a reminder.

**Comment by jkramer** [comment]
That's been fixed long time ago, please use a recent checkout from GitHub.

**Comment by its-danny** [comment]
Ah, so it does! Thanks, I marked the AUR package (updated Sep. 2009) as out of date, hopefully whoever is maintaing it will update it.

**Comment by jkramer** [comment]
Problem seems to be solved then. :)

**Comment by MrBryan** [comment]
checked out latest github and tried various branches.. still get "couldn't scrobble track(s)" on master and on others, last.fm seems to know what track i'm playing but it won't report it as having been played with finished

**Comment by MrBryan** [comment]
sorry my fault i had a version from macPorts in my path that was overriding after installing the new version
